import { dir } from "i18next";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../globals.css";
import { MainInfo } from "@/components/MainInfo";
import { Header } from "@/components/header/Header";
import { PageProps } from "@/shared/types";

const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway-sans",
  subsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<
  {
    children: React.ReactNode;
  } & PageProps
>) {
  const { lng } = params;
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${raleway.variable} antialiased`}>
        <Header lng={lng} />
        <MainInfo lng={lng} />
        {children}
      </body>
    </html>
  );
}
