import { dir } from "i18next";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../globals.css";
import { MainInfo } from "@/components/MainInfo";
import { Header } from "@/components/Header";
import { initTranslations } from "../i18n";
import { navigations } from "@/shared/static/menuNavigations";

const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway-sans",
  subsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps) {
  const {lng} = params
  const { t } = await initTranslations(lng);
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${raleway.variable} antialiased`}>
        <Header data={navigations(t)} />
        <MainInfo t={t} />
        {children}
      </body>
    </html>
  );
}
